### PR TITLE
Small additions 

### LINKED ISSUE #37: Firmware deletion does not work
I created a new Kali environment and installed an EMBArk successfully. I did some FW scans and I wanted to delete a firmware image from EMBArk. Delete -> OK and EMBArk logged out and "Account successfully deleted." message displayed.
I made the registration with the same user / password and I was ablo to log back in and I got the previous results but the selected FW image was there.
The firmware image deletion destroys the registration and does not work as expected.

I reproduced the same scenarion on a different environment and I got the same result.

VMware Workstation Pro
Kali 2022.1
Actual EMBArk

### PR DESCRIPTION
**Pull request by BenediktMKuehne**
**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
---
* adds https on port 443
* adds Scan_time into reportdashboard
* Fix NX-Pie issue
* Fix Fw-Delete issue
* Addition of Templates

**What is the current behavior?**
---
Server runs on http only

**What is the new behavior (if this is a feature change)? If possible add a screenshot.**
---
Server offers https with self-signed certificate
(which is useless when using locally )

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
---
Depends on your deployment-configuration.
since `run-server.sh` changes, you should reinstall EMBArk IF you want to use the SSL encryption.

**Other information**:
------
https: and wss: functionality would need to be tested in a server-client setting that is not on localhost

### CODE REVIEW

File: run-server.sh [hunk 1]
```diff
@@ -30,7 +30,7 @@ cleaner() {
   fuser -k 80/tcp
   fuser -k 8001/tcp
   killall -9 -q "*daphne*"
-  #TODO add kill for all p /app/emba
+  killall -9 -q "*/app/emba/emba.sh*"
   kill -9 "$(pgrep "manage.py runapscheduler")"     # TODO add non null cond
```
Comment (m-1-k-3) [inline run-server.sh]: could we use pkill?

File: installer.sh [hunk 2]
```diff
@@ -425,9 +455,15 @@ uninstall (){
   #9 stop daemon
   systemctl stop embark.service
   systemctl disable embark.service
+  git checkout HEAD -- embark.service
+  systemctl daemon-reload
 
   #10 reset ownership etc
-  # TODO
+  # TODO delte the dns resolve
```
Comment (m-1-k-3) [inline installer.sh]: typo ... delete

File: .github/ISSUE_TEMPLATE/bug_report.md [hunk 3]
```diff
@@ -0,0 +1,31 @@
...
+assignees: ''
+
+---
+
+**Describe the bug**
+A clear and concise description of what the bug is.
+
+**To Reproduce**
+Steps to reproduce the behavior:
+1. EMBA installation (dev-mode/default mode)
```
Comment (m-1-k-3) [inline .github/ISSUE_TEMPLATE/bug_report.md]: EMBArk

File: .github/ISSUE_TEMPLATE/bug_report.md [hunk 4]
```diff
@@ -0,0 +1,31 @@
...
+2. Use the firmware available here: <Insert URL>
+3. Start EMBA with the following parameters: sudo ./emba.sh <insert further parameters>
```
Comment (m-1-k-3) [inline .github/ISSUE_TEMPLATE/bug_report.md]: EMBArk and start command form EMBArk

**Review by m-1-k-3 — APPROVED** [review]
Thank you ... good work
